### ISSUE TITLE
Plugin fails with no clear error

### ISSUE THREAD

**Issue by jakubgs** [KrauseFx/fastlane-plugin-clean_testflight_testers#10]
I'm using `2.125.2` and when i run the plugin I get through:
```
Login to iTunes Connect (****)
Login successful
Fetching all TestFlight testers, this might take a few minutes, depending on the number of testers
```
Just fine, but then when the plugin hits the first user to remove:
```
Removing tester abcdefg@gmail.com due to inactivity from app ID 1122334455...
```
I get back some HTML:
```
+---------------+-----------+
|       Lane Context        |
+---------------+-----------+
| PLATFORM_NAME | ios       |
| LANE_NAME     | ios clean |
+---------------+-----------+
[19:22:20]: <!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Not Found</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>

+------+--------------------------+-------------+
|               fastlane summary                |
+------+--------------------------+-------------+
| Step | Action                   | Time (in s) |
+------+--------------------------+-------------+
| 💥   | clean_testflight_testers | 754         |
+------+--------------------------+-------------+

[19:22:20]: fastlane finished with errors
```
The stack trace looks like this:
```
{{gems_location}}/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/client.rb:321:in `handle_response'
{{gems_location}}/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/client.rb:208:in `delete_tester_from_app'
{{gems_location}}/gems/fastlane-2.121.1/spaceship/lib/spaceship/test_flight/tester.rb:124:in `remove_from_app!'
{{gems_location}}/gems/fastlane-plugin-clean_testflight_testers-0.2.0/lib/fastlane/plugin/clean_testflight_testers/actions/clean_testflight_testers_action.rb:57:in `remove_tester'
{{gems_location}}/gems/fastlane-plugin-clean_testflight_testers-0.2.0/lib/fastlane/plugin/clean_testflight_testers/actions/clean_testflight_testers_action.rb:39:in `block in run'
{{gems_location}}/gems/fastlane-plugin-clean_testflight_testers-0.2.0/lib/fastlane/plugin/clean_testflight_testers/actions/clean_testflight_testers_action.rb:22:in `each'
{{gems_location}}/gems/fastlane-plugin-clean_testflight_testers-0.2.0/lib/fastlane/plugin/clean_testflight_testers/actions/clean_testflight_testers_action.rb:22:in `run'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
Fastfile:238:in `block (2 levels) in parsing_binding'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/lane.rb:33:in `call'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
{{gems_location}}/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
{{gems_location}}/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
{{gems_location}}/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
{{gems_location}}/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
{{gems_location}}/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
{{gems_location}}/gems/fastlane-2.121.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
{{gems_location}}/gems/fastlane-2.121.1/bin/fastlane:23:in `<top (required)>'
{{ruby_location}}/bin/fastlane:23:in `load'
{{ruby_location}}/bin/fastlane:23:in `<top (required)>'
```
Which isn't very helpful. Not sure what to make of this.

**Comment by hsousa** [comment]
I'm pretty sure this is the same issue I fixed in 0.3.0.

Closing, please re-open if it keeps happening.
